Vib-push-new
aruiz14/charts pull request #9
Opened 2022-04-25 15:23 UTC by javsalgar

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

2022-04-25 15:30 UTC, aruiz14 requested changes

2022-04-25 15:30 UTC, aruiz14 commented on .github/workflows/vib-publish.yaml
> +  vib-push: # verify in multiple target platforms
```suggestion
  vib-publish:
```

2022-04-25 15:30 UTC, aruiz14 commented on .github/workflows/vib-publish.yaml
> +          VIB_ENV_S3_URL: ${{ secrets.S3_URL }}
We need to change the secret to use `/bitnami`, or add it here

2022-04-26 10:12 UTC, javsalgar commented on .github/workflows/vib-publish.yaml
> +          VIB_ENV_S3_URL: ${{ secrets.S3_URL }}
I added it below

2022-04-26 15:00 UTC, merged